services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: always

  # ClickHouse service
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_PORT1}:${CLICKHOUSE_PORT1}"
      - "${CLICKHOUSE_PORT2}:${CLICKHOUSE_PORT2}"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: always

  # Bun + Elysia application service
  bun-elysia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-elysia
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGO_URI: ${MONGO_URI}
      CLICKHOUSE_URL: ${CLICKHOUSE_URL}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    depends_on:
      - mongodb
      - clickhouse
    restart: always

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  clickhouse_data:
    driver: local
