services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: always

  # Bun + Elysia application service
  bun-elysia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-elysia
    ports:
      - '3000:3000' # Exposing Bun app on port 3000
    environment: #mongodb://root:password@127.0.0.1:27017
      MONGO_URI: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
