services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: always

  # ClickHouse service
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      CLICKHOUSE_DB: events_db
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: always

  # Bun + Elysia application service
  bun-elysia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-elysia
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017
      CLICKHOUSE_URL: http://clickhouse:8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
    depends_on:
      - mongodb
      - clickhouse
    restart: always

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  clickhouse_data:
    driver: local